package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "generate bundled defaults: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	workingDir, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("get working directory: %w", err)
	}

	repoRoot := filepath.Clean(filepath.Join(workingDir, "..", ".."))
	skillsRoot := filepath.Join(repoRoot, ".agents", "skills")
	outputPath := filepath.Join(workingDir, "defaults_generated.go")

	files, err := collectSkills(skillsRoot)
	if err != nil {
		return err
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by go generate ./internal/skills. DO NOT EDIT.\n")
	buf.WriteString("package skills\n\n")
	buf.WriteString("var bundledDefaults = map[string]string{\n")
	for _, relPath := range files {
		content, err := os.ReadFile(filepath.Join(skillsRoot, filepath.FromSlash(relPath)))
		if err != nil {
			return fmt.Errorf("read %s: %w", relPath, err)
		}
		fmt.Fprintf(&buf, "\t%q: %s,\n", relPath, strconv.Quote(string(content)))
	}
	buf.WriteString("}\n")

	if err := os.WriteFile(outputPath, buf.Bytes(), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", outputPath, err)
	}

	return nil
}

func collectSkills(root string) ([]string, error) {
	entries := make([]string, 0)
	err := filepath.WalkDir(root, func(path string, d os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if d.IsDir() || !strings.EqualFold(d.Name(), "SKILL.md") {
			return nil
		}

		relPath, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		entries = append(entries, filepath.ToSlash(relPath))
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("walk %s: %w", root, err)
	}

	sort.Strings(entries)
	return entries, nil
}
