// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.26.0
// source: pkg/pluginrpc/plugin.proto

package pluginrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EmeraldPlugin_Describe_FullMethodName       = "/pluginrpc.EmeraldPlugin/Describe"
	EmeraldPlugin_ValidateConfig_FullMethodName = "/pluginrpc.EmeraldPlugin/ValidateConfig"
	EmeraldPlugin_ExecuteAction_FullMethodName  = "/pluginrpc.EmeraldPlugin/ExecuteAction"
	EmeraldPlugin_ToolDefinition_FullMethodName = "/pluginrpc.EmeraldPlugin/ToolDefinition"
	EmeraldPlugin_ExecuteTool_FullMethodName    = "/pluginrpc.EmeraldPlugin/ExecuteTool"
)

// EmeraldPluginClient is the client API for EmeraldPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmeraldPluginClient interface {
	Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error)
	ValidateConfig(ctx context.Context, in *ValidateConfigRequest, opts ...grpc.CallOption) (*ValidateConfigResponse, error)
	ExecuteAction(ctx context.Context, in *ExecuteActionRequest, opts ...grpc.CallOption) (*ExecuteActionResponse, error)
	ToolDefinition(ctx context.Context, in *ToolDefinitionRequest, opts ...grpc.CallOption) (*ToolDefinitionResponse, error)
	ExecuteTool(ctx context.Context, in *ExecuteToolRequest, opts ...grpc.CallOption) (*ExecuteToolResponse, error)
}

type emeraldPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewEmeraldPluginClient(cc grpc.ClientConnInterface) EmeraldPluginClient {
	return &emeraldPluginClient{cc}
}

func (c *emeraldPluginClient) Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeResponse)
	err := c.cc.Invoke(ctx, EmeraldPlugin_Describe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emeraldPluginClient) ValidateConfig(ctx context.Context, in *ValidateConfigRequest, opts ...grpc.CallOption) (*ValidateConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateConfigResponse)
	err := c.cc.Invoke(ctx, EmeraldPlugin_ValidateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emeraldPluginClient) ExecuteAction(ctx context.Context, in *ExecuteActionRequest, opts ...grpc.CallOption) (*ExecuteActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteActionResponse)
	err := c.cc.Invoke(ctx, EmeraldPlugin_ExecuteAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emeraldPluginClient) ToolDefinition(ctx context.Context, in *ToolDefinitionRequest, opts ...grpc.CallOption) (*ToolDefinitionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToolDefinitionResponse)
	err := c.cc.Invoke(ctx, EmeraldPlugin_ToolDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emeraldPluginClient) ExecuteTool(ctx context.Context, in *ExecuteToolRequest, opts ...grpc.CallOption) (*ExecuteToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteToolResponse)
	err := c.cc.Invoke(ctx, EmeraldPlugin_ExecuteTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmeraldPluginServer is the server API for EmeraldPlugin service.
// All implementations must embed UnimplementedEmeraldPluginServer
// for forward compatibility.
type EmeraldPluginServer interface {
	Describe(context.Context, *DescribeRequest) (*DescribeResponse, error)
	ValidateConfig(context.Context, *ValidateConfigRequest) (*ValidateConfigResponse, error)
	ExecuteAction(context.Context, *ExecuteActionRequest) (*ExecuteActionResponse, error)
	ToolDefinition(context.Context, *ToolDefinitionRequest) (*ToolDefinitionResponse, error)
	ExecuteTool(context.Context, *ExecuteToolRequest) (*ExecuteToolResponse, error)
	mustEmbedUnimplementedEmeraldPluginServer()
}

// UnimplementedEmeraldPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEmeraldPluginServer struct{}

func (UnimplementedEmeraldPluginServer) Describe(context.Context, *DescribeRequest) (*DescribeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedEmeraldPluginServer) ValidateConfig(context.Context, *ValidateConfigRequest) (*ValidateConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateConfig not implemented")
}
func (UnimplementedEmeraldPluginServer) ExecuteAction(context.Context, *ExecuteActionRequest) (*ExecuteActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteAction not implemented")
}
func (UnimplementedEmeraldPluginServer) ToolDefinition(context.Context, *ToolDefinitionRequest) (*ToolDefinitionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ToolDefinition not implemented")
}
func (UnimplementedEmeraldPluginServer) ExecuteTool(context.Context, *ExecuteToolRequest) (*ExecuteToolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteTool not implemented")
}
func (UnimplementedEmeraldPluginServer) mustEmbedUnimplementedEmeraldPluginServer() {}
func (UnimplementedEmeraldPluginServer) testEmbeddedByValue()                       {}

// UnsafeEmeraldPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmeraldPluginServer will
// result in compilation errors.
type UnsafeEmeraldPluginServer interface {
	mustEmbedUnimplementedEmeraldPluginServer()
}

func RegisterEmeraldPluginServer(s grpc.ServiceRegistrar, srv EmeraldPluginServer) {
	// If the following call panics, it indicates UnimplementedEmeraldPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EmeraldPlugin_ServiceDesc, srv)
}

func _EmeraldPlugin_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmeraldPluginServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmeraldPlugin_Describe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmeraldPluginServer).Describe(ctx, req.(*DescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmeraldPlugin_ValidateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmeraldPluginServer).ValidateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmeraldPlugin_ValidateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmeraldPluginServer).ValidateConfig(ctx, req.(*ValidateConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmeraldPlugin_ExecuteAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmeraldPluginServer).ExecuteAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmeraldPlugin_ExecuteAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmeraldPluginServer).ExecuteAction(ctx, req.(*ExecuteActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmeraldPlugin_ToolDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToolDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmeraldPluginServer).ToolDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmeraldPlugin_ToolDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmeraldPluginServer).ToolDefinition(ctx, req.(*ToolDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmeraldPlugin_ExecuteTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmeraldPluginServer).ExecuteTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmeraldPlugin_ExecuteTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmeraldPluginServer).ExecuteTool(ctx, req.(*ExecuteToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EmeraldPlugin_ServiceDesc is the grpc.ServiceDesc for EmeraldPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmeraldPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pluginrpc.EmeraldPlugin",
	HandlerType: (*EmeraldPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Describe",
			Handler:    _EmeraldPlugin_Describe_Handler,
		},
		{
			MethodName: "ValidateConfig",
			Handler:    _EmeraldPlugin_ValidateConfig_Handler,
		},
		{
			MethodName: "ExecuteAction",
			Handler:    _EmeraldPlugin_ExecuteAction_Handler,
		},
		{
			MethodName: "ToolDefinition",
			Handler:    _EmeraldPlugin_ToolDefinition_Handler,
		},
		{
			MethodName: "ExecuteTool",
			Handler:    _EmeraldPlugin_ExecuteTool_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/pluginrpc/plugin.proto",
}
