// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.26.0
// source: pkg/pluginrpc/plugin.proto

package pluginrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DescribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeRequest) Reset() {
	*x = DescribeRequest{}
	mi := &file_pkg_pluginrpc_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeRequest) ProtoMessage() {}

func (x *DescribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginrpc_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeRequest.ProtoReflect.Descriptor instead.
func (*DescribeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pluginrpc_plugin_proto_rawDescGZIP(), []int{0}
}

type DescribeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PluginInfoJson []byte                 `protobuf:"bytes,1,opt,name=plugin_info_json,json=pluginInfoJson,proto3" json:"plugin_info_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DescribeResponse) Reset() {
	*x = DescribeResponse{}
	mi := &file_pkg_pluginrpc_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResponse) ProtoMessage() {}

func (x *DescribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginrpc_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResponse.ProtoReflect.Descriptor instead.
func (*DescribeResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pluginrpc_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *DescribeResponse) GetPluginInfoJson() []byte {
	if x != nil {
		return x.PluginInfoJson
	}
	return nil
}

type ValidateConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ConfigJson    []byte                 `protobuf:"bytes,2,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateConfigRequest) Reset() {
	*x = ValidateConfigRequest{}
	mi := &file_pkg_pluginrpc_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateConfigRequest) ProtoMessage() {}

func (x *ValidateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginrpc_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateConfigRequest.ProtoReflect.Descriptor instead.
func (*ValidateConfigRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pluginrpc_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateConfigRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ValidateConfigRequest) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

type ValidateConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateConfigResponse) Reset() {
	*x = ValidateConfigResponse{}
	mi := &file_pkg_pluginrpc_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateConfigResponse) ProtoMessage() {}

func (x *ValidateConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginrpc_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateConfigResponse.ProtoReflect.Descriptor instead.
func (*ValidateConfigResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pluginrpc_plugin_proto_rawDescGZIP(), []int{3}
}

type ExecuteActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ConfigJson    []byte                 `protobuf:"bytes,2,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	InputJson     []byte                 `protobuf:"bytes,3,opt,name=input_json,json=inputJson,proto3" json:"input_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteActionRequest) Reset() {
	*x = ExecuteActionRequest{}
	mi := &file_pkg_pluginrpc_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteActionRequest) ProtoMessage() {}

func (x *ExecuteActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginrpc_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteActionRequest.ProtoReflect.Descriptor instead.
func (*ExecuteActionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pluginrpc_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteActionRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ExecuteActionRequest) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

func (x *ExecuteActionRequest) GetInputJson() []byte {
	if x != nil {
		return x.InputJson
	}
	return nil
}

type ExecuteActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OutputJson    []byte                 `protobuf:"bytes,1,opt,name=output_json,json=outputJson,proto3" json:"output_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteActionResponse) Reset() {
	*x = ExecuteActionResponse{}
	mi := &file_pkg_pluginrpc_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteActionResponse) ProtoMessage() {}

func (x *ExecuteActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginrpc_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteActionResponse.ProtoReflect.Descriptor instead.
func (*ExecuteActionResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pluginrpc_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *ExecuteActionResponse) GetOutputJson() []byte {
	if x != nil {
		return x.OutputJson
	}
	return nil
}

type ToolDefinitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	MetaJson      []byte                 `protobuf:"bytes,2,opt,name=meta_json,json=metaJson,proto3" json:"meta_json,omitempty"`
	ConfigJson    []byte                 `protobuf:"bytes,3,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolDefinitionRequest) Reset() {
	*x = ToolDefinitionRequest{}
	mi := &file_pkg_pluginrpc_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolDefinitionRequest) ProtoMessage() {}

func (x *ToolDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginrpc_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolDefinitionRequest.ProtoReflect.Descriptor instead.
func (*ToolDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pluginrpc_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *ToolDefinitionRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ToolDefinitionRequest) GetMetaJson() []byte {
	if x != nil {
		return x.MetaJson
	}
	return nil
}

func (x *ToolDefinitionRequest) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

type ToolDefinitionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DefinitionJson []byte                 `protobuf:"bytes,1,opt,name=definition_json,json=definitionJson,proto3" json:"definition_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ToolDefinitionResponse) Reset() {
	*x = ToolDefinitionResponse{}
	mi := &file_pkg_pluginrpc_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolDefinitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolDefinitionResponse) ProtoMessage() {}

func (x *ToolDefinitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginrpc_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolDefinitionResponse.ProtoReflect.Descriptor instead.
func (*ToolDefinitionResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pluginrpc_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *ToolDefinitionResponse) GetDefinitionJson() []byte {
	if x != nil {
		return x.DefinitionJson
	}
	return nil
}

type ExecuteToolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ConfigJson    []byte                 `protobuf:"bytes,2,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	ArgsJson      []byte                 `protobuf:"bytes,3,opt,name=args_json,json=argsJson,proto3" json:"args_json,omitempty"`
	InputJson     []byte                 `protobuf:"bytes,4,opt,name=input_json,json=inputJson,proto3" json:"input_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteToolRequest) Reset() {
	*x = ExecuteToolRequest{}
	mi := &file_pkg_pluginrpc_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteToolRequest) ProtoMessage() {}

func (x *ExecuteToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginrpc_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteToolRequest.ProtoReflect.Descriptor instead.
func (*ExecuteToolRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pluginrpc_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *ExecuteToolRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ExecuteToolRequest) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

func (x *ExecuteToolRequest) GetArgsJson() []byte {
	if x != nil {
		return x.ArgsJson
	}
	return nil
}

func (x *ExecuteToolRequest) GetInputJson() []byte {
	if x != nil {
		return x.InputJson
	}
	return nil
}

type ExecuteToolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResultJson    []byte                 `protobuf:"bytes,1,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteToolResponse) Reset() {
	*x = ExecuteToolResponse{}
	mi := &file_pkg_pluginrpc_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteToolResponse) ProtoMessage() {}

func (x *ExecuteToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pluginrpc_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteToolResponse.ProtoReflect.Descriptor instead.
func (*ExecuteToolResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pluginrpc_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *ExecuteToolResponse) GetResultJson() []byte {
	if x != nil {
		return x.ResultJson
	}
	return nil
}

var File_pkg_pluginrpc_plugin_proto protoreflect.FileDescriptor

const file_pkg_pluginrpc_plugin_proto_rawDesc = "" +
	"\n" +
	"\x1apkg/pluginrpc/plugin.proto\x12\tpluginrpc\"\x11\n" +
	"\x0fDescribeRequest\"<\n" +
	"\x10DescribeResponse\x12(\n" +
	"\x10plugin_info_json\x18\x01 \x01(\fR\x0epluginInfoJson\"Q\n" +
	"\x15ValidateConfigRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vconfig_json\x18\x02 \x01(\fR\n" +
	"configJson\"\x18\n" +
	"\x16ValidateConfigResponse\"o\n" +
	"\x14ExecuteActionRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vconfig_json\x18\x02 \x01(\fR\n" +
	"configJson\x12\x1d\n" +
	"\n" +
	"input_json\x18\x03 \x01(\fR\tinputJson\"8\n" +
	"\x15ExecuteActionResponse\x12\x1f\n" +
	"\voutput_json\x18\x01 \x01(\fR\n" +
	"outputJson\"n\n" +
	"\x15ToolDefinitionRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tmeta_json\x18\x02 \x01(\fR\bmetaJson\x12\x1f\n" +
	"\vconfig_json\x18\x03 \x01(\fR\n" +
	"configJson\"A\n" +
	"\x16ToolDefinitionResponse\x12'\n" +
	"\x0fdefinition_json\x18\x01 \x01(\fR\x0edefinitionJson\"\x8a\x01\n" +
	"\x12ExecuteToolRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vconfig_json\x18\x02 \x01(\fR\n" +
	"configJson\x12\x1b\n" +
	"\targs_json\x18\x03 \x01(\fR\bargsJson\x12\x1d\n" +
	"\n" +
	"input_json\x18\x04 \x01(\fR\tinputJson\"6\n" +
	"\x13ExecuteToolResponse\x12\x1f\n" +
	"\vresult_json\x18\x01 \x01(\fR\n" +
	"resultJson2\xa4\x03\n" +
	"\rEmeraldPlugin\x12C\n" +
	"\bDescribe\x12\x1a.pluginrpc.DescribeRequest\x1a\x1b.pluginrpc.DescribeResponse\x12U\n" +
	"\x0eValidateConfig\x12 .pluginrpc.ValidateConfigRequest\x1a!.pluginrpc.ValidateConfigResponse\x12R\n" +
	"\rExecuteAction\x12\x1f.pluginrpc.ExecuteActionRequest\x1a .pluginrpc.ExecuteActionResponse\x12U\n" +
	"\x0eToolDefinition\x12 .pluginrpc.ToolDefinitionRequest\x1a!.pluginrpc.ToolDefinitionResponse\x12L\n" +
	"\vExecuteTool\x12\x1d.pluginrpc.ExecuteToolRequest\x1a\x1e.pluginrpc.ExecuteToolResponseB;Z9github.com/FlameInTheDark/emerald/pkg/pluginrpc;pluginrpcb\x06proto3"

var (
	file_pkg_pluginrpc_plugin_proto_rawDescOnce sync.Once
	file_pkg_pluginrpc_plugin_proto_rawDescData []byte
)

func file_pkg_pluginrpc_plugin_proto_rawDescGZIP() []byte {
	file_pkg_pluginrpc_plugin_proto_rawDescOnce.Do(func() {
		file_pkg_pluginrpc_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_pluginrpc_plugin_proto_rawDesc), len(file_pkg_pluginrpc_plugin_proto_rawDesc)))
	})
	return file_pkg_pluginrpc_plugin_proto_rawDescData
}

var file_pkg_pluginrpc_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pkg_pluginrpc_plugin_proto_goTypes = []any{
	(*DescribeRequest)(nil),        // 0: pluginrpc.DescribeRequest
	(*DescribeResponse)(nil),       // 1: pluginrpc.DescribeResponse
	(*ValidateConfigRequest)(nil),  // 2: pluginrpc.ValidateConfigRequest
	(*ValidateConfigResponse)(nil), // 3: pluginrpc.ValidateConfigResponse
	(*ExecuteActionRequest)(nil),   // 4: pluginrpc.ExecuteActionRequest
	(*ExecuteActionResponse)(nil),  // 5: pluginrpc.ExecuteActionResponse
	(*ToolDefinitionRequest)(nil),  // 6: pluginrpc.ToolDefinitionRequest
	(*ToolDefinitionResponse)(nil), // 7: pluginrpc.ToolDefinitionResponse
	(*ExecuteToolRequest)(nil),     // 8: pluginrpc.ExecuteToolRequest
	(*ExecuteToolResponse)(nil),    // 9: pluginrpc.ExecuteToolResponse
}
var file_pkg_pluginrpc_plugin_proto_depIdxs = []int32{
	0, // 0: pluginrpc.EmeraldPlugin.Describe:input_type -> pluginrpc.DescribeRequest
	2, // 1: pluginrpc.EmeraldPlugin.ValidateConfig:input_type -> pluginrpc.ValidateConfigRequest
	4, // 2: pluginrpc.EmeraldPlugin.ExecuteAction:input_type -> pluginrpc.ExecuteActionRequest
	6, // 3: pluginrpc.EmeraldPlugin.ToolDefinition:input_type -> pluginrpc.ToolDefinitionRequest
	8, // 4: pluginrpc.EmeraldPlugin.ExecuteTool:input_type -> pluginrpc.ExecuteToolRequest
	1, // 5: pluginrpc.EmeraldPlugin.Describe:output_type -> pluginrpc.DescribeResponse
	3, // 6: pluginrpc.EmeraldPlugin.ValidateConfig:output_type -> pluginrpc.ValidateConfigResponse
	5, // 7: pluginrpc.EmeraldPlugin.ExecuteAction:output_type -> pluginrpc.ExecuteActionResponse
	7, // 8: pluginrpc.EmeraldPlugin.ToolDefinition:output_type -> pluginrpc.ToolDefinitionResponse
	9, // 9: pluginrpc.EmeraldPlugin.ExecuteTool:output_type -> pluginrpc.ExecuteToolResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_pluginrpc_plugin_proto_init() }
func file_pkg_pluginrpc_plugin_proto_init() {
	if File_pkg_pluginrpc_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_pluginrpc_plugin_proto_rawDesc), len(file_pkg_pluginrpc_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_pluginrpc_plugin_proto_goTypes,
		DependencyIndexes: file_pkg_pluginrpc_plugin_proto_depIdxs,
		MessageInfos:      file_pkg_pluginrpc_plugin_proto_msgTypes,
	}.Build()
	File_pkg_pluginrpc_plugin_proto = out.File
	file_pkg_pluginrpc_plugin_proto_goTypes = nil
	file_pkg_pluginrpc_plugin_proto_depIdxs = nil
}
